arm:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.005
  kinematics_solver_attempts: 3
  mode: global
  position_scale: 1.0
  rotation_scale: 0.05
  position_threshold: 0.01
  orientation_threshold: 0.25
  cost_threshold: 0.001
  minimal_displacement_weight: 0.0
  gd_step_size: 0.0001