# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    gripper_controller:
      type: position_controllers/GripperActionController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - DOF_1
      - DOF_2
      - DOF_3
      - DOF_4
      - DOF_5
    command_interfaces:
      - position
    state_interfaces:
      - position
    allow_nonzero_velocity_at_trajectory_end: true
strawberry_picking_rpi_hand_controller:
  ros__parameters:
    joint: GRIPPER