<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="multi_functional_servo_bracket_with_servo">
    <xacro:macro name="multi_functional_servo_bracket_with_servo" params="prefix *bracket_origin *joint">
        <link name="${prefix}_multi_functional_servo_bracket_with_servo">
            <inertial>
                <xacro:insert_block name="bracket_origin"/>
                <mass value="0.0"/>
                <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
            </inertial>
            <visual name="">
                <xacro:insert_block name="bracket_origin"/>
                <geometry>
                    <mesh filename="package://strawberry_picking_rpi_description/meshes/multi_functional_servo_bracket_with_servo.stl" scale="0.001 0.001 0.001"/>
                </geometry>
                <material name="aluminum"/> 
            </visual>
            <collision>
                <origin xyz="
                0.0 
                ${multi_functional_servo_bracket_with_servo_y_size/2} 
                0.013" 
                rpy="
                0.0
                0.0
                0.0"
                />
                <geometry>
                    <box size="${multi_functional_servo_bracket_with_servo_x_size} 
                               ${multi_functional_servo_bracket_with_servo_y_size} 
                               ${multi_functional_servo_bracket_with_servo_z_size}"
                    />
                </geometry>
            </collision>
        </link>

        <xacro:insert_block name="joint"/>
    </xacro:macro>
</robot>