<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="strawberry_picking_rpi">
    <!-- based on 2x2 plank measurements 1.5in x 1.5in x 1.5in -->
    <xacro:property name="base_x_size" value="0.0381"/>
    <xacro:property name="base_y_size" value="0.0381"/>
    <xacro:property name="base_z_size" value="0.0381"/>

    <xacro:property name="u_type_robot_waist_bracket_x_size" value="0.090"/>
    <xacro:property name="u_type_robot_waist_bracket_y_size" value="0.045"/>
    <xacro:property name="u_type_robot_waist_bracket_z_size" value="0.028"/>

    <xacro:property name="multi_functional_servo_bracket_with_servo_x_size" value="0.057"/>
    <xacro:property name="multi_functional_servo_bracket_with_servo_y_size" value="0.025"/>
    <xacro:property name="multi_functional_servo_bracket_with_servo_z_size" value="0.050"/>
    <xacro:property name="mg996r_velocity_6v" value="6.98133333333"/>
    <xacro:property name="mg996r_velocity_4dot8v" value="5.51157894737"/>

    <xacro:property name="long_u_type_servo_bracket_x_size" value="0.055"/>
    <xacro:property name="long_u_type_servo_bracket_y_size" value="0.025"/>
    <xacro:property name="long_u_type_servo_bracket_z_size" value="0.065"/>

    <xacro:property name="l_type_servo_bracket_x_size" value="0.037"/>
    <xacro:property name="l_type_servo_bracket_y_size" value="0.025"/>
    <xacro:property name="l_type_servo_bracket_z_size" value="0.025"/>

    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/u_type_robot_waist_bracket.urdf.xacro"/>
    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/multi_functional_servo_bracket_with_servo.urdf.xacro"/>
    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/long_u_type_servo_bracket.urdf.xacro"/>
    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/l_type_servo_bracket.urdf.xacro"/>
    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/gripper.urdf.xacro"/>
    
    <material name="wood">
        <color rgba="${164/255} ${116/255} ${73/255} 1.0"/>
        <texture filename=""/>
    </material>
    <material name="aluminum">
        <color rgba="${136/255} ${139/255} ${141/255} 1.0"/>
    </material>
    <material name="black_plastic">
        <color rgba="${15/255} ${15/255} ${19/255} 1.0"/>
    </material>

    <!-- the base link is the plank where the robot sits on -->
    <link name="base_link">
        <visual name="base_link">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x_size} 
                           ${base_y_size} 
                           ${base_z_size}"
                />
            </geometry>
            <material name="wood"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x_size} 
                           ${base_y_size} 
                           ${base_z_size}"
                />
            </geometry>
        </collision>
    </link>

    <!-- these blocks define the base of the robotic arm -->
    <xacro:u_type_robot_waist_bracket prefix="1" parent_link="base_link"> 
        <origin xyz="
        0.0
        ${u_type_robot_waist_bracket_y_size/2}
        ${u_type_robot_waist_bracket_z_size/2}" 
        rpy="
        0.0 
        0.0
        0.0"
        />
        <origin xyz="
        0.0
        0.0
        ${base_z_size/2}" 
        rpy="
        0.0 
        0.0
        0.0"
        />
    </xacro:u_type_robot_waist_bracket>
    <xacro:u_type_robot_waist_bracket prefix="2" parent_link="1_u_type_robot_waist_bracket"> 
        <origin xyz="
        0.0
        ${u_type_robot_waist_bracket_y_size/2}
        ${u_type_robot_waist_bracket_z_size/2}" 
        rpy="
        0.0 
        0.0
        0.0"
        />
        <origin xyz="
        0.0
        0.0
        0.0" 
        rpy="
        0.0 
        0.0
        ${pi}"
        />
    </xacro:u_type_robot_waist_bracket>
    <xacro:u_type_robot_waist_bracket prefix="3" parent_link="1_u_type_robot_waist_bracket"> 
        <origin xyz="
        0.0
        0.0
        ${u_type_robot_waist_bracket_y_size/2}" 
        rpy="
        ${pi/2}
        0.0
        0.0"
        />
        <origin xyz="
        0.0
        0.03025
        ${u_type_robot_waist_bracket_z_size}" 
        rpy="
        0.0 
        0.0
        0.0"
        />
    </xacro:u_type_robot_waist_bracket>
    <xacro:multi_functional_servo_bracket_with_servo prefix="1"> 
        <origin xyz="
        0.0 
        ${multi_functional_servo_bracket_with_servo_y_size/2+0.0008} 
        0.01"
        rpy="
        0.0
        0.0
        ${pi}"
        />
        <joint name="1_multi_functional_servo_bracket_with_servo_to_3_u_type_robot_waist_bracket" type="fixed">
            <origin xyz="
            0.0
            ${-u_type_robot_waist_bracket_z_size/2}
            0.03025" 
            rpy="
            0.0 
            0.0
            ${pi}"
            />
            <parent link="3_u_type_robot_waist_bracket"/>
            <child link="1_multi_functional_servo_bracket_with_servo"/>
        </joint>
    </xacro:multi_functional_servo_bracket_with_servo>

    <!-- the next blocks will define the second segment of the robotic arm -->
    <xacro:long_u_type_servo_bracket prefix="1"> 
        <origin xyz="
        ${-long_u_type_servo_bracket_z_size+0.0125}
        ${-long_u_type_servo_bracket_y_size/2+0.0025}
        ${-long_u_type_servo_bracket_x_size/2+0.002}" 
        rpy="
        0.0
        ${pi/2}
        0.0"
        />
        <joint name="DOF_1" type="revolute">
            <origin xyz="
            0.0095
            ${multi_functional_servo_bracket_with_servo_y_size/2+0.0015}
            ${multi_functional_servo_bracket_with_servo_z_size-0.014}" 
            rpy="
            0.0 
            0.0
            ${-pi}"
            />
            <limit lower="0" upper="${pi}" effort="1000" velocity="${mg996r_velocity_6v}"/>
            <axis xyz="0.0 0.0 1"/>
            <parent link="1_multi_functional_servo_bracket_with_servo"/>
            <child link="1_long_u_type_servo_bracket"/>
        </joint>
    </xacro:long_u_type_servo_bracket>
    <xacro:multi_functional_servo_bracket_with_servo prefix="2" is_reversed="_reversed"> 
        <origin xyz="
        0.0
        ${-multi_functional_servo_bracket_with_servo_y_size/2-0.0015} 
        0.009"
        rpy="
        0.0
        0.0
        0.0"
        />
        <joint name="2_multi_functional_servo_bracket_with_servo_to_1_long_u_type_servo_bracket" type="fixed">
            <origin xyz="
            -0.012
            -0.011
            0.003" 
            rpy="
            ${pi/2}
            ${pi}
            ${pi}"
            />
            <parent link="1_long_u_type_servo_bracket"/>
            <child link="2_multi_functional_servo_bracket_with_servo"/>
        </joint>
    </xacro:multi_functional_servo_bracket_with_servo>
    <xacro:long_u_type_servo_bracket prefix="2"> 
        <origin xyz="
        ${-long_u_type_servo_bracket_z_size+0.0125}
        ${-long_u_type_servo_bracket_y_size/2+0.0025}
        ${-long_u_type_servo_bracket_x_size/2+0.001}" 
        rpy="
        0.0
        ${pi/2}
        0.0"
        />
        <joint name="DOF_2" type="revolute">
            <origin xyz="
            0.0095
            ${-multi_functional_servo_bracket_with_servo_y_size/2-0.0015}
            ${multi_functional_servo_bracket_with_servo_z_size-0.014}" 
            rpy="
            0.0 
            0.0
            0.0"
            />
            <limit lower="0" upper="${pi}" effort="1000" velocity="${mg996r_velocity_6v}"/>
            <axis xyz="0.0 0.0 1"/>
            <parent link="2_multi_functional_servo_bracket_with_servo"/>
            <child link="2_long_u_type_servo_bracket"/>
        </joint>
    </xacro:long_u_type_servo_bracket>
    <xacro:long_u_type_servo_bracket prefix="3"> 
        <origin xyz="
        ${-long_u_type_servo_bracket_z_size+0.012}
        ${-long_u_type_servo_bracket_y_size/2+0.002}
        ${-long_u_type_servo_bracket_x_size/2+0.002}" 
        rpy="
        0.0
        ${-pi/2}
        0.0"
        />
        <joint name="3_long_u_type_servo_bracket_to_2_long_u_type_servo_bracket" type="fixed">
            <origin xyz="
            0.0
            0.0
            0.0" 
            rpy="
            0.0 
            0.0
            0.0"
            />
            <parent link="2_long_u_type_servo_bracket"/>
            <child link="3_long_u_type_servo_bracket"/>
        </joint>
    </xacro:long_u_type_servo_bracket>

    <!-- the next blocks will define the third segment of the robotic arm -->
    <xacro:multi_functional_servo_bracket_with_servo prefix="3" is_reversed="_reversed"> 
        <origin xyz="
        0.0095
        0.0
        ${-multi_functional_servo_bracket_with_servo_y_size-0.003}" 
        rpy="
        0.0
        0.0
        ${pi}"
        />
        <joint name="DOF_3" type="revolute">
            <origin xyz="
            ${-long_u_type_servo_bracket_x_size*2+0.0045}
            0.0
            0.0" 
            rpy="
            0.0
            0.0
            ${pi/2}"
            />
            <limit lower="0" upper="${pi}" effort="1000" velocity="${mg996r_velocity_6v}"/>
            <axis xyz="0.0 0.0 1"/>
            <parent link="3_long_u_type_servo_bracket"/>
            <child link="3_multi_functional_servo_bracket_with_servo"/>
        </joint>
    </xacro:multi_functional_servo_bracket_with_servo>
    <xacro:l_type_servo_bracket prefix="1" parent_link="3_multi_functional_servo_bracket_with_servo">
        <origin xyz="
        0.0
        -0.0062
        ${l_type_servo_bracket_z_size/2-0.002}" 
        rpy="
        0.0
        0.0
        0.0"
        />
        <origin xyz="
        0.0205
        ${-multi_functional_servo_bracket_with_servo_y_size/2-0.001}
        ${-multi_functional_servo_bracket_with_servo_z_size/2}" 
        rpy="
        ${3*pi/2} 
        ${pi/2}
        0.0"
        />
    </xacro:l_type_servo_bracket>
    <xacro:long_u_type_servo_bracket prefix="4"> 
        <origin xyz="
        0.0
        0.0
        ${-long_u_type_servo_bracket_y_size/2+0.0045}" 
        rpy="
        ${pi/2}
        0.0
        0.0"
        />
        <joint name="4_long_u_type_servo_bracket_to_1_l_type_servo_bracket" type="fixed">
            <origin xyz="
            0.0
            ${-l_type_servo_bracket_y_size}
            ${l_type_servo_bracket_z_size/2}" 
            rpy="
            0.0 
            0.0
            0.0"
            />
            <parent link="1_l_type_servo_bracket"/>
            <child link="4_long_u_type_servo_bracket"/>
        </joint>
    </xacro:long_u_type_servo_bracket>

    <!-- the next block will define the fourth segment of the robotic arm -->
    <xacro:multi_functional_servo_bracket_with_servo prefix="4"> 
        <origin xyz="
        0.0095
        0.0
        ${-multi_functional_servo_bracket_with_servo_y_size}" 
        rpy="
        0.0
        0.0
        0.0"
        />
        <joint name="DOF_4" type="revolute">
            <origin xyz="
            ${-long_u_type_servo_bracket_y_size}
            ${-long_u_type_servo_bracket_x_size+0.0025}
            ${0.002}" 
            rpy="
            ${pi}
            ${pi/2}
            0.0"
            />
            <limit lower="0" upper="${pi}" effort="1000" velocity="${mg996r_velocity_6v}"/>
            <axis xyz="0.0 0.0 1"/>
            <parent link="4_long_u_type_servo_bracket"/>
            <child link="4_multi_functional_servo_bracket_with_servo"/>
        </joint>
    </xacro:multi_functional_servo_bracket_with_servo>
    <xacro:multi_functional_servo_bracket_with_servo prefix="5" is_reversed="_reversed"> 
        <origin xyz="
        0.007
        ${multi_functional_servo_bracket_with_servo_y_size/2}
        0.0" 
        rpy="
        ${pi}
        ${-pi/2}
        0.0"
        />
        <joint name="5_multi_functional_servo_bracket_with_servo_to_4_multi_functional_servo_bracket_with_servo" type="fixed">
            <origin xyz="
            ${multi_functional_servo_bracket_with_servo_z_size/2-0.004}
            ${multi_functional_servo_bracket_with_servo_y_size/2}
            ${-multi_functional_servo_bracket_with_servo_z_size/2+0.003}" 
            rpy="
            0.0
            0.0
            0.0"
            />
            <parent link="4_multi_functional_servo_bracket_with_servo"/>
            <child link="5_multi_functional_servo_bracket_with_servo"/>
        </joint>
    </xacro:multi_functional_servo_bracket_with_servo>
    <xacro:gripper prefix="1"> 
        <joint name="DOF_5" type="revolute">
            <parent link="5_multi_functional_servo_bracket_with_servo"/>
            <child link="gripper_base"/>
            <origin xyz="0.034 0.012 0.01" rpy="${pi/2} 0.0 ${pi/2}"/>
            <axis xyz="0.0 0.0 1"/>
            <limit lower="0" upper="${pi}" effort="1000" velocity="${mg996r_velocity_6v}"/>
            <axis xyz="0.0 0.0 1"/>
            
        </joint>
    </xacro:gripper>
    <!-- ros2_control part, commented out for moveit2 -->
    <!--<xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/strawberry_picking_rpi_control.urdf.xacro"/>
    <xacro:controllers/>-->
</robot>