<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="strawberry_picking_rpi">
    <!-- based on 2x2 plank measurements 1.5in x 1.5in x 1.5in -->
    <xacro:property name="base_x_size" value="0.0381"/>
    <xacro:property name="base_y_size" value="0.0381"/>
    <xacro:property name="base_z_size" value="0.0381"/>

    <xacro:property name="u_type_robot_waist_bracket_x_size" value="0.090"/>
    <xacro:property name="u_type_robot_waist_bracket_y_size" value="0.045"/>
    <xacro:property name="u_type_robot_waist_bracket_z_size" value="0.028"/>

    <xacro:include filename="$(find strawberry_picking_rpi_description)/urdf/u_type_robot_waist_bracket.urdf.xacro"/>
    

    <material name="wood">
        <color rgba="${164/255} ${116/255} ${73/255} 1.0"/>
        <texture filename=""/>
    </material>

    <material name="aluminum">
        <color rgba="${136/255} ${139/255} ${141/255} 1.0"/>
        <texture filename="file_path"/>
    </material>

    <link name="base_link">
        <inertial>
            <origin xyz="0.0 0.0 ${u_type_robot_waist_bracket_z_size/2}" rpy="0.0 0.0 0.0"/>
            <mass value="0.0"/>
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0"/>
        </inertial>
        <visual name="base_link">
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x_size} 
                           ${base_y_size} 
                           ${base_z_size}"
                />
            </geometry>
            <material name="wood"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${base_x_size} 
                           ${base_y_size} 
                           ${base_z_size}"
                />
            </geometry>
        </collision>
    </link>

    <xacro:u_type_robot_waist_bracket prefix="01" parent_link="base_link"> 
        <origin xyz=
        "0.0
        0.0
        0.0" 
                rpy=
        "0.0 
        0.0
        0.0"
        />
        <origin xyz="0.0 0.0 ${base_z_size/2}" rpy="0.0 0.0 0.0"/>
    </xacro:u_type_robot_waist_bracket>

</robot>